package main

import (
	"crypto/md5"
	"encoding/hex"
	"io/ioutil"
	"net/http"
	"regexp"
)

var regex = map[string]string{
	"Yopmail":                  "@yopmail.com",
	"Firebase":                 "[-a-zA-Z0-9@:%._~#=]{1,256}.firebaseio.com",
	"AWS Access Key ID Value":  "(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}",
	"FCM Server Key":           "AAAA[a-zA-Z0-9_-]{7}:[a-zA-Z0-9_-]{140}",
	"slack_token":              "(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})",
	"slack_webhook":            "https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}",
	"facebook_oauth":           "[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].{0,30}['\"\\s][0-9a-f]{32}['\"\\s]",
	"twitter_oauth":            "[t|T][w|W][i|I][t|T][t|T][e|E][r|R].{0,30}['\"\\s][0-9a-zA-Z]{35,44}['\"\\s]",
	"heroku_api":               "[h|H][e|E][r|R][o|O][k|K][u|U].{0,30}[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}",
	"mailgun_api":              "key-[0-9a-zA-Z]{32}",
	"mailchamp_api":            "[0-9a-f]{32}-us[0-9]{1,2}",
	"picatic_api":              "sk_live_[0-9a-z]{32}",
	"google_oauth_id":          "[0-9(+-[0-9A-Za-z_]{32}.apps.googleusercontent.com",
	"ipinfo token":             "ipinfo.io?token=",
	"google_api":               "AIza[0-9A-Za-z-_]{35}",
	"google_captcha":           "^6[0-9a-zA-Z_-]{39}$",
	"google_oauth":             "ya29\\.[0-9A-Za-z\\-_]+",
	"amazon_aws_access_key_id": "AKIA[0-9A-Z]{16}",
	"amazon_mws_auth_token":    "amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
	//"amazonaws_url":                 "s3\\.amazonaws.com[/]+|[a-zA-Z0-9_-]*\\.s3\\.amazonaws.com",
	"facebook_access_token":         "EAACEdEose0cBA[0-9A-Za-z]+",
	"mailgun_api_key":               "key-[0-9a-zA-Z]{32}",
	"twilio_api_key":                "K[0-9a-fA-F]{32}$",
	"twilio_account_sid":            "C[a-zA-Z0-9_\\-]{32}$",
	"twilio_app_sid":                "P[a-zA-Z0-9_\\-]{32}$",
	"paypal_braintree_access_token": "access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}",
	"square_oauth_secret":           "sq0csp-[ 0-9A-Za-z\\-_]{43}",
	"square_access_token":           "sqOatp-[0-9A-Za-z\\-_]{22}",
	"stripe_standard_api":           "sk_live_[0-9a-zA-Z]{24}",
	"stripe_restricted_api":         "rk_live_[0-9a-zA-Z]{24}",
	"github_access_token":           "[a-zA-Z0-9_-]*:[a-zA-Z0-9_\\-]+@github\\.com*",
	"private_ssh_key":               "-----BEGIN PRIVATE KEY-----[a-zA-Z0-9\\S]{100,}-----END PRIVATE KEY-----",
	"private_rsa_key":               "-----BEGIN RSA PRIVATE KEY-----[a-zA-Z0-9\\S]{100,}-----END RSA PRIVATE KEY-----",
	"AMAZON_KEY":                    "([^A-Z0-9]|^)(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{12,}",
	"Authorization":                 "^Bearer[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$",
	"accessToken":                   "^acesstoken=[0-9]{13,17}",
	"vtex-key":                      "vtex-api-(appkey|apptoken)",
	"email":                         "(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$)",
	"api.runtime.dev":               " https://api.runtime.dev/tlp?apikey",
	"app.sportdataapi.com":          "https://app.sportdataapi.com/api",
	"api.mediastack.com":            "https://api.mediastack.com/v1",
	"api.screenshotlayer.com":       "http://api.screenshotlayer.com/api/capture ",
	"api.languagelayer.com":         "http://api.languagelayer.com/detect?access_key=",
	"app.zenscrape.com":             "https://app.zenscrape.com/api/v1/get?apikey=",
	"Http usernamme password":       "(ftp|ftps|http|https)://[A-Za-z0-9-_:.~]+(@)",
	"credentials-disclosure[3]":     "api[_-]?key(=| =|:| :)",
	"credentials-disclosure[4]":     "zopim[_-]?account[_-]?key(=| =|:| :)",
	"credentials-disclosure[5]":     "zhuliang[_-]?gh[_-]?token(=| =|:| :)",
	"credentials-disclosure[6]":     "zensonatypepassword(=| =|:| :)",
	"credentials-disclosure[7]":     "zendesk[_-]?travis[_-]?github(=| =|:| :)",
	"credentials-disclosure[8]":     "yt[_-]?server[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[9]":     "yt[_-]?partner[_-]?refresh[_-]?token(=| =|:| :)",
	"credentials-disclosure[10]":    "yt[_-]?partner[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[11]":    "yt[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[12]":    "yt[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[13]":    "yt[_-]?account[_-]?refresh[_-]?token(=| =|:| :)",
	"credentials-disclosure[14]":    "yt[_-]?account[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[15]":    "yangshun[_-]?gh[_-]?token(=| =|:| :)",
	"credentials-disclosure[16]":    "yangshun[_-]?gh[_-]?password(=| =|:| :)",
	"credentials-disclosure[17]":    "www[_-]?googleapis[_-]?com(=| =|:| :)",
	"credentials-disclosure[18]":    "wpt[_-]?ssh[_-]?private[_-]?key[_-]?base64(=| =|:| :)",
	"credentials-disclosure[19]":    "wpt[_-]?ssh[_-]?connect(=| =|:| :)",
	"credentials-disclosure[20]":    "wpt[_-]?report[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[21]":    "wpt[_-]?prepare[_-]?dir(=| =|:| :)",
	"credentials-disclosure[22]":    "wpt[_-]?db[_-]?user(=| =|:| :)",
	"credentials-disclosure[23]":    "wpt[_-]?db[_-]?password(=| =|:| :)",
	"credentials-disclosure[24]":    "wporg[_-]?password(=| =|:| :)",
	"credentials-disclosure[25]":    "wpjm[_-]?phpunit[_-]?google[_-]?geocode[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[26]":    "wordpress[_-]?db[_-]?user(=| =|:| :)",
	"credentials-disclosure[27]":    "wordpress[_-]?db[_-]?password(=| =|:| :)",
	"credentials-disclosure[28]":    "wincert[_-]?password(=| =|:| :)",
	"credentials-disclosure[29]":    "widget[_-]?test[_-]?server(=| =|:| :)",
	"credentials-disclosure[30]":    "widget[_-]?fb[_-]?password[_-]?3(=| =|:| :)",
	"credentials-disclosure[31]":    "widget[_-]?fb[_-]?password[_-]?2(=| =|:| :)",
	"credentials-disclosure[32]":    "widget[_-]?fb[_-]?password(=| =|:| :)",
	"credentials-disclosure[33]":    "widget[_-]?basic[_-]?password[_-]?5(=| =|:| :)",
	"credentials-disclosure[34]":    "widget[_-]?basic[_-]?password[_-]?4(=| =|:| :)",
	"credentials-disclosure[35]":    "widget[_-]?basic[_-]?password[_-]?3(=| =|:| :)",
	"credentials-disclosure[36]":    "widget[_-]?basic[_-]?password[_-]?2(=| =|:| :)",
	"credentials-disclosure[37]":    "widget[_-]?basic[_-]?password(=| =|:| :)",
	"credentials-disclosure[38]":    "watson[_-]?password(=| =|:| :)",
	"credentials-disclosure[39]":    "watson[_-]?device[_-]?password(=| =|:| :)",
	"credentials-disclosure[40]":    "watson[_-]?conversation[_-]?password(=| =|:| :)",
	"credentials-disclosure[41]":    "wakatime[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[42]":    "vscetoken(=| =|:| :)",
	"credentials-disclosure[43]":    "visual[_-]?recognition[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[44]":    "virustotal[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[45]":    "vip[_-]?github[_-]?deploy[_-]?key[_-]?pass(=| =|:| :)",
	"credentials-disclosure[46]":    "vip[_-]?github[_-]?deploy[_-]?key(=| =|:| :)",
	"credentials-disclosure[47]":    "vip[_-]?github[_-]?build[_-]?repo[_-]?deploy[_-]?key(=| =|:| :)",
	"credentials-disclosure[48]":    "v[_-]?sfdc[_-]?password(=| =|:| :)",
	"credentials-disclosure[49]":    "v[_-]?sfdc[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[50]":    "usertravis(=| =|:| :)",
	"credentials-disclosure[51]":    "user[_-]?assets[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[52]":    "user[_-]?assets[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[53]":    "use[_-]?ssh(=| =|:| :)",
	"credentials-disclosure[54]":    "us[_-]?east[_-]?1[_-]?elb[_-]?amazonaws[_-]?com(=| =|:| :)",
	"credentials-disclosure[55]":    "urban[_-]?secret(=| =|:| :)",
	"credentials-disclosure[56]":    "urban[_-]?master[_-]?secret(=| =|:| :)",
	"credentials-disclosure[57]":    "urban[_-]?key(=| =|:| :)",
	"credentials-disclosure[58]":    "unity[_-]?serial(=| =|:| :)",
	"credentials-disclosure[59]":    "unity[_-]?password(=| =|:| :)",
	"credentials-disclosure[60]":    "twitteroauthaccesstoken(=| =|:| :)",
	"credentials-disclosure[61]":    "twitteroauthaccesssecret(=| =|:| :)",
	"credentials-disclosure[62]":    "twitter[_-]?consumer[_-]?secret(=| =|:| :)",
	"credentials-disclosure[63]":    "twitter[_-]?consumer[_-]?key(=| =|:| :)",
	"credentials-disclosure[64]":    "twine[_-]?password(=| =|:| :)",
	"credentials-disclosure[65]":    "twilio[_-]?token(=| =|:| :)",
	"credentials-disclosure[66]":    "twilio[_-]?sid(=| =|:| :)",
	"credentials-disclosure[67]":    "twilio[_-]?configuration[_-]?sid(=| =|:| :)",
	"credentials-disclosure[68]":    "twilio[_-]?chat[_-]?account[_-]?api[_-]?service(=| =|:| :)",
	"credentials-disclosure[69]":    "twilio[_-]?api[_-]?secret(=| =|:| :)",
	"credentials-disclosure[70]":    "twilio[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[71]":    "trex[_-]?okta[_-]?client[_-]?token(=| =|:| :)",
	"credentials-disclosure[72]":    "trex[_-]?client[_-]?token(=| =|:| :)",
	"credentials-disclosure[73]":    "travis[_-]?token(=| =|:| :)",
	"credentials-disclosure[74]":    "travis[_-]?secure[_-]?env[_-]?vars(=| =|:| :)",
	"credentials-disclosure[75]":    "travis[_-]?pull[_-]?request(=| =|:| :)",
	"credentials-disclosure[76]":    "travis[_-]?gh[_-]?token(=| =|:| :)",
	"credentials-disclosure[77]":    "travis[_-]?e2e[_-]?token(=| =|:| :)",
	"credentials-disclosure[78]":    "travis[_-]?com[_-]?token(=| =|:| :)",
	"credentials-disclosure[79]":    "travis[_-]?branch(=| =|:| :)",
	"credentials-disclosure[80]":    "travis[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[81]":    "travis[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[82]":    "token[_-]?core[_-]?java(=| =|:| :)",
	"credentials-disclosure[83]":    "thera[_-]?oss[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[84]":    "tester[_-]?keys[_-]?password(=| =|:| :)",
	"credentials-disclosure[85]":    "test[_-]?test(=| =|:| :)",
	"credentials-disclosure[86]":    "test[_-]?github[_-]?token(=| =|:| :)",
	"credentials-disclosure[87]":    "tesco[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[88]":    "svn[_-]?pass(=| =|:| :)",
	"credentials-disclosure[89]":    "surge[_-]?token(=| =|:| :)",
	"credentials-disclosure[90]":    "surge[_-]?login(=| =|:| :)",
	"credentials-disclosure[91]":    "stripe[_-]?public(=| =|:| :)",
	"credentials-disclosure[92]":    "stripe[_-]?private(=| =|:| :)",
	"credentials-disclosure[93]":    "strip[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[94]":    "strip[_-]?publishable[_-]?key(=| =|:| :)",
	"credentials-disclosure[95]":    "stormpath[_-]?api[_-]?key[_-]?secret(=| =|:| :)",
	"credentials-disclosure[96]":    "stormpath[_-]?api[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[97]":    "starship[_-]?auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[98]":    "starship[_-]?account[_-]?sid(=| =|:| :)",
	"credentials-disclosure[99]":    "star[_-]?test[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[100]":   "star[_-]?test[_-]?location(=| =|:| :)",
	"credentials-disclosure[101]":   "star[_-]?test[_-]?bucket(=| =|:| :)",
	"credentials-disclosure[102]":   "star[_-]?test[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[103]":   "staging[_-]?base[_-]?url[_-]?runscope(=| =|:| :)",
	"credentials-disclosure[104]":   "ssmtp[_-]?config(=| =|:| :)",
	"credentials-disclosure[105]":   "sshpass(=| =|:| :)",
	"credentials-disclosure[106]":   "srcclr[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[107]":   "square[_-]?reader[_-]?sdk[_-]?repository[_-]?password(=| =|:| :)",
	"credentials-disclosure[108]":   "sqssecretkey(=| =|:| :)",
	"credentials-disclosure[109]":   "sqsaccesskey(=| =|:| :)",
	"credentials-disclosure[110]":   "spring[_-]?mail[_-]?password(=| =|:| :)",
	"credentials-disclosure[111]":   "spotify[_-]?api[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[112]":   "spotify[_-]?api[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[113]":   "spaces[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[114]":   "spaces[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[115]":   "soundcloud[_-]?password(=| =|:| :)",
	"credentials-disclosure[116]":   "soundcloud[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[117]":   "sonatypepassword(=| =|:| :)",
	"credentials-disclosure[118]":   "sonatype[_-]?token[_-]?user(=| =|:| :)",
	"credentials-disclosure[119]":   "sonatype[_-]?token[_-]?password(=| =|:| :)",
	"credentials-disclosure[120]":   "sonatype[_-]?password(=| =|:| :)",
	"credentials-disclosure[121]":   "sonatype[_-]?pass(=| =|:| :)",
	"credentials-disclosure[122]":   "sonatype[_-]?nexus[_-]?password(=| =|:| :)",
	"credentials-disclosure[123]":   "sonatype[_-]?gpg[_-]?passphrase(=| =|:| :)",
	"credentials-disclosure[124]":   "sonatype[_-]?gpg[_-]?key[_-]?name(=| =|:| :)",
	"credentials-disclosure[125]":   "sonar[_-]?token(=| =|:| :)",
	"credentials-disclosure[126]":   "sonar[_-]?project[_-]?key(=| =|:| :)",
	"credentials-disclosure[127]":   "sonar[_-]?organization[_-]?key(=| =|:| :)",
	"credentials-disclosure[128]":   "socrata[_-]?password(=| =|:| :)",
	"credentials-disclosure[129]":   "socrata[_-]?app[_-]?token(=| =|:| :)",
	"credentials-disclosure[130]":   "snyk[_-]?token(=| =|:| :)",
	"credentials-disclosure[131]":   "snyk[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[132]":   "snoowrap[_-]?refresh[_-]?token(=| =|:| :)",
	"credentials-disclosure[133]":   "snoowrap[_-]?password(=| =|:| :)",
	"credentials-disclosure[134]":   "snoowrap[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[135]":   "slate[_-]?user[_-]?email(=| =|:| :)",
	"credentials-disclosure[136]":   "slash[_-]?developer[_-]?space[_-]?key(=| =|:| :)",
	"credentials-disclosure[137]":   "slash[_-]?developer[_-]?space(=| =|:| :)",
	"credentials-disclosure[138]":   "signing[_-]?key[_-]?sid(=| =|:| :)",
	"credentials-disclosure[139]":   "signing[_-]?key[_-]?secret(=| =|:| :)",
	"credentials-disclosure[140]":   "signing[_-]?key[_-]?password(=| =|:| :)",
	"credentials-disclosure[141]":   "signing[_-]?key(=| =|:| :)",
	"credentials-disclosure[142]":   "setsecretkey(=| =|:| :)",
	"credentials-disclosure[143]":   "setdstsecretkey(=| =|:| :)",
	"credentials-disclosure[144]":   "setdstaccesskey(=| =|:| :)",
	"credentials-disclosure[145]":   "ses[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[146]":   "ses[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[147]":   "service[_-]?account[_-]?secret(=| =|:| :)",
	"credentials-disclosure[148]":   "sentry[_-]?key(=| =|:| :)",
	"credentials-disclosure[149]":   "sentry[_-]?endpoint(=| =|:| :)",
	"credentials-disclosure[150]":   "sentry[_-]?default[_-]?org(=| =|:| :)",
	"credentials-disclosure[151]":   "sentry[_-]?auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[152]":   "sendwithus[_-]?key(=| =|:| :)",
	"credentials-disclosure[153]":   "sendgrid[_-]?username(=| =|:| :)",
	"credentials-disclosure[154]":   "sendgrid[_-]?user(=| =|:| :)",
	"credentials-disclosure[155]":   "sendgrid[_-]?password(=| =|:| :)",
	"credentials-disclosure[156]":   "sendgrid[_-]?key(=| =|:| :)",
	"credentials-disclosure[157]":   "sendgrid[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[158]":   "sendgrid(=| =|:| :)",
	"credentials-disclosure[159]":   "selion[_-]?selenium[_-]?host(=| =|:| :)",
	"credentials-disclosure[160]":   "selion[_-]?log[_-]?level[_-]?dev(=| =|:| :)",
	"credentials-disclosure[161]":   "segment[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[162]":   "secretkey(=| =|:| :)",
	"credentials-disclosure[163]":   "secretaccesskey(=| =|:| :)",
	"credentials-disclosure[164]":   "secret[_-]?key[_-]?base(=| =|:| :)",
	"credentials-disclosure[165]":   "secret[_-]?9(=| =|:| :)",
	"credentials-disclosure[166]":   "secret[_-]?8(=| =|:| :)",
	"credentials-disclosure[167]":   "secret[_-]?7(=| =|:| :)",
	"credentials-disclosure[168]":   "secret[_-]?6(=| =|:| :)",
	"credentials-disclosure[169]":   "secret[_-]?5(=| =|:| :)",
	"credentials-disclosure[170]":   "secret[_-]?4(=| =|:| :)",
	"credentials-disclosure[171]":   "secret[_-]?3(=| =|:| :)",
	"credentials-disclosure[172]":   "secret[_-]?2(=| =|:| :)",
	"credentials-disclosure[173]":   "secret[_-]?11(=| =|:| :)",
	"credentials-disclosure[174]":   "secret[_-]?10(=| =|:| :)",
	"credentials-disclosure[175]":   "secret[_-]?1(=| =|:| :)",
	"credentials-disclosure[176]":   "secret[_-]?0(=| =|:| :)",
	"credentials-disclosure[177]":   "sdr[_-]?token(=| =|:| :)",
	"credentials-disclosure[178]":   "scrutinizer[_-]?token(=| =|:| :)",
	"credentials-disclosure[179]":   "sauce[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[180]":   "sandbox[_-]?aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[181]":   "sandbox[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[182]":   "sandbox[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[183]":   "salesforce[_-]?bulk[_-]?test[_-]?security[_-]?token(=| =|:| :)",
	"credentials-disclosure[184]":   "salesforce[_-]?bulk[_-]?test[_-]?password(=| =|:| :)",
	"credentials-disclosure[185]":   "sacloud[_-]?api(=| =|:| :)",
	"credentials-disclosure[186]":   "sacloud[_-]?access[_-]?token[_-]?secret(=| =|:| :)",
	"credentials-disclosure[187]":   "sacloud[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[188]":   "s3[_-]?user[_-]?secret(=| =|:| :)",
	"credentials-disclosure[189]":   "s3[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[190]":   "s3[_-]?secret[_-]?assets(=| =|:| :)",
	"credentials-disclosure[191]":   "s3[_-]?secret[_-]?app[_-]?logs(=| =|:| :)",
	"credentials-disclosure[192]":   "s3[_-]?key[_-]?assets(=| =|:| :)",
	"credentials-disclosure[193]":   "s3[_-]?key[_-]?app[_-]?logs(=| =|:| :)",
	"credentials-disclosure[194]":   "s3[_-]?key(=| =|:| :)",
	"credentials-disclosure[195]":   "s3[_-]?external[_-]?3[_-]?amazonaws[_-]?com(=| =|:| :)",
	"credentials-disclosure[196]":   "s3[_-]?bucket[_-]?name[_-]?assets(=| =|:| :)",
	"credentials-disclosure[197]":   "s3[_-]?bucket[_-]?name[_-]?app[_-]?logs(=| =|:| :)",
	"credentials-disclosure[198]":   "s3[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[199]":   "s3[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[200]":   "rubygems[_-]?auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[201]":   "rtd[_-]?store[_-]?pass(=| =|:| :)",
	"credentials-disclosure[202]":   "rtd[_-]?key[_-]?pass(=| =|:| :)",
	"credentials-disclosure[203]":   "route53[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[204]":   "ropsten[_-]?private[_-]?key(=| =|:| :)",
	"credentials-disclosure[205]":   "rinkeby[_-]?private[_-]?key(=| =|:| :)",
	"credentials-disclosure[206]":   "rest[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[207]":   "repotoken(=| =|:| :)",
	"credentials-disclosure[208]":   "reporting[_-]?webdav[_-]?url(=| =|:| :)",
	"credentials-disclosure[209]":   "reporting[_-]?webdav[_-]?pwd(=| =|:| :)",
	"credentials-disclosure[210]":   "release[_-]?token(=| =|:| :)",
	"credentials-disclosure[211]":   "release[_-]?gh[_-]?token(=| =|:| :)",
	"credentials-disclosure[212]":   "registry[_-]?secure(=| =|:| :)",
	"credentials-disclosure[213]":   "registry[_-]?pass(=| =|:| :)",
	"credentials-disclosure[214]":   "refresh[_-]?token(=| =|:| :)",
	"credentials-disclosure[215]":   "rediscloud[_-]?url(=| =|:| :)",
	"credentials-disclosure[216]":   "redis[_-]?stunnel[_-]?urls(=| =|:| :)",
	"credentials-disclosure[217]":   "randrmusicapiaccesstoken(=| =|:| :)",
	"credentials-disclosure[218]":   "rabbitmq[_-]?password(=| =|:| :)",
	"credentials-disclosure[219]":   "quip[_-]?token(=| =|:| :)",
	"credentials-disclosure[220]":   "qiita[_-]?token(=| =|:| :)",
	"credentials-disclosure[221]":   "pypi[_-]?passowrd(=| =|:| :)",
	"credentials-disclosure[222]":   "pushover[_-]?token(=| =|:| :)",
	"credentials-disclosure[223]":   "publish[_-]?secret(=| =|:| :)",
	"credentials-disclosure[224]":   "publish[_-]?key(=| =|:| :)",
	"credentials-disclosure[225]":   "publish[_-]?access(=| =|:| :)",
	"credentials-disclosure[226]":   "project[_-]?config(=| =|:| :)",
	"credentials-disclosure[227]":   "prod[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[228]":   "prod[_-]?password(=| =|:| :)",
	"credentials-disclosure[229]":   "prod[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[230]":   "private[_-]?signing[_-]?password(=| =|:| :)",
	"credentials-disclosure[231]":   "pring[_-]?mail[_-]?username(=| =|:| :)",
	"credentials-disclosure[232]":   "preferred[_-]?username(=| =|:| :)",
	"credentials-disclosure[233]":   "prebuild[_-]?auth(=| =|:| :)",
	"credentials-disclosure[234]":   "postgresql[_-]?pass(=| =|:| :)",
	"credentials-disclosure[235]":   "postgresql[_-]?db(=| =|:| :)",
	"credentials-disclosure[236]":   "postgres[_-]?env[_-]?postgres[_-]?password(=| =|:| :)",
	"credentials-disclosure[237]":   "postgres[_-]?env[_-]?postgres[_-]?db(=| =|:| :)",
	"credentials-disclosure[238]":   "plugin[_-]?password(=| =|:| :)",
	"credentials-disclosure[239]":   "plotly[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[240]":   "places[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[241]":   "places[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[242]":   "pg[_-]?host(=| =|:| :)",
	"credentials-disclosure[243]":   "pg[_-]?database(=| =|:| :)",
	"credentials-disclosure[244]":   "personal[_-]?secret(=| =|:| :)",
	"credentials-disclosure[245]":   "personal[_-]?key(=| =|:| :)",
	"credentials-disclosure[246]":   "percy[_-]?token(=| =|:| :)",
	"credentials-disclosure[247]":   "percy[_-]?project(=| =|:| :)",
	"credentials-disclosure[248]":   "paypal[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[249]":   "passwordtravis(=| =|:| :)",
	"credentials-disclosure[250]":   "parse[_-]?js[_-]?key(=| =|:| :)",
	"credentials-disclosure[251]":   "pagerduty[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[252]":   "packagecloud[_-]?token(=| =|:| :)",
	"credentials-disclosure[253]":   "ossrh[_-]?username(=| =|:| :)",
	"credentials-disclosure[254]":   "ossrh[_-]?secret(=| =|:| :)",
	"credentials-disclosure[255]":   "ossrh[_-]?password(=| =|:| :)",
	"credentials-disclosure[256]":   "ossrh[_-]?pass(=| =|:| :)",
	"credentials-disclosure[257]":   "ossrh[_-]?jira[_-]?password(=| =|:| :)",
	"credentials-disclosure[258]":   "os[_-]?password(=| =|:| :)",
	"credentials-disclosure[259]":   "os[_-]?auth[_-]?url(=| =|:| :)",
	"credentials-disclosure[260]":   "org[_-]?project[_-]?gradle[_-]?sonatype[_-]?nexus[_-]?password(=| =|:| :)",
	"credentials-disclosure[261]":   "org[_-]?gradle[_-]?project[_-]?sonatype[_-]?nexus[_-]?password(=| =|:| :)",
	"credentials-disclosure[262]":   "openwhisk[_-]?key(=| =|:| :)",
	"credentials-disclosure[263]":   "open[_-]?whisk[_-]?key(=| =|:| :)",
	"credentials-disclosure[264]":   "onesignal[_-]?user[_-]?auth[_-]?key(=| =|:| :)",
	"credentials-disclosure[265]":   "onesignal[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[266]":   "omise[_-]?skey(=| =|:| :)",
	"credentials-disclosure[267]":   "omise[_-]?pubkey(=| =|:| :)",
	"credentials-disclosure[268]":   "omise[_-]?pkey(=| =|:| :)",
	"credentials-disclosure[269]":   "omise[_-]?key(=| =|:| :)",
	"credentials-disclosure[270]":   "okta[_-]?oauth2[_-]?clientsecret(=| =|:| :)",
	"credentials-disclosure[271]":   "okta[_-]?oauth2[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[272]":   "okta[_-]?client[_-]?token(=| =|:| :)",
	"credentials-disclosure[273]":   "ofta[_-]?secret(=| =|:| :)",
	"credentials-disclosure[274]":   "ofta[_-]?region(=| =|:| :)",
	"credentials-disclosure[275]":   "ofta[_-]?key(=| =|:| :)",
	"credentials-disclosure[276]":   "octest[_-]?password(=| =|:| :)",
	"credentials-disclosure[277]":   "octest[_-]?app[_-]?username(=| =|:| :)",
	"credentials-disclosure[278]":   "octest[_-]?app[_-]?password(=| =|:| :)",
	"credentials-disclosure[279]":   "oc[_-]?pass(=| =|:| :)",
	"credentials-disclosure[280]":   "object[_-]?store[_-]?creds(=| =|:| :)",
	"credentials-disclosure[281]":   "object[_-]?store[_-]?bucket(=| =|:| :)",
	"credentials-disclosure[282]":   "object[_-]?storage[_-]?region[_-]?name(=| =|:| :)",
	"credentials-disclosure[283]":   "object[_-]?storage[_-]?password(=| =|:| :)",
	"credentials-disclosure[284]":   "oauth[_-]?token(=| =|:| :)",
	"credentials-disclosure[285]":   "numbers[_-]?service[_-]?pass(=| =|:| :)",
	"credentials-disclosure[286]":   "nuget[_-]?key(=| =|:| :)",
	"credentials-disclosure[287]":   "nuget[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[288]":   "nuget[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[289]":   "npm[_-]?token(=| =|:| :)",
	"credentials-disclosure[290]":   "npm[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[291]":   "npm[_-]?password(=| =|:| :)",
	"credentials-disclosure[292]":   "npm[_-]?email(=| =|:| :)",
	"credentials-disclosure[293]":   "npm[_-]?auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[294]":   "npm[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[295]":   "npm[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[296]":   "now[_-]?token(=| =|:| :)",
	"credentials-disclosure[297]":   "non[_-]?token(=| =|:| :)",
	"credentials-disclosure[298]":   "node[_-]?pre[_-]?gyp[_-]?secretaccesskey(=| =|:| :)",
	"credentials-disclosure[299]":   "node[_-]?pre[_-]?gyp[_-]?github[_-]?token(=| =|:| :)",
	"credentials-disclosure[300]":   "node[_-]?pre[_-]?gyp[_-]?accesskeyid(=| =|:| :)",
	"credentials-disclosure[301]":   "node[_-]?env(=| =|:| :)",
	"credentials-disclosure[302]":   "ngrok[_-]?token(=| =|:| :)",
	"credentials-disclosure[303]":   "ngrok[_-]?auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[304]":   "nexuspassword(=| =|:| :)",
	"credentials-disclosure[305]":   "nexus[_-]?password(=| =|:| :)",
	"credentials-disclosure[306]":   "new[_-]?relic[_-]?beta[_-]?token(=| =|:| :)",
	"credentials-disclosure[307]":   "netlify[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[308]":   "nativeevents(=| =|:| :)",
	"credentials-disclosure[309]":   "mysqlsecret(=| =|:| :)",
	"credentials-disclosure[310]":   "mysqlmasteruser(=| =|:| :)",
	"credentials-disclosure[311]":   "mysql[_-]?username(=| =|:| :)",
	"credentials-disclosure[312]":   "mysql[_-]?user(=| =|:| :)",
	"credentials-disclosure[313]":   "mysql[_-]?root[_-]?password(=| =|:| :)",
	"credentials-disclosure[314]":   "mysql[_-]?password(=| =|:| :)",
	"credentials-disclosure[315]":   "mysql[_-]?hostname(=| =|:| :)",
	"credentials-disclosure[316]":   "mysql[_-]?database(=| =|:| :)",
	"credentials-disclosure[317]":   "my[_-]?secret[_-]?env(=| =|:| :)",
	"credentials-disclosure[318]":   "multi[_-]?workspace[_-]?sid(=| =|:| :)",
	"credentials-disclosure[319]":   "multi[_-]?workflow[_-]?sid(=| =|:| :)",
	"credentials-disclosure[320]":   "multi[_-]?disconnect[_-]?sid(=| =|:| :)",
	"credentials-disclosure[321]":   "multi[_-]?connect[_-]?sid(=| =|:| :)",
	"credentials-disclosure[322]":   "multi[_-]?bob[_-]?sid(=| =|:| :)",
	"credentials-disclosure[323]":   "minio[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[324]":   "minio[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[325]":   "mile[_-]?zero[_-]?key(=| =|:| :)",
	"credentials-disclosure[326]":   "mh[_-]?password(=| =|:| :)",
	"credentials-disclosure[327]":   "mh[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[328]":   "mg[_-]?public[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[329]":   "mg[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[330]":   "mapboxaccesstoken(=| =|:| :)",
	"credentials-disclosure[331]":   "mapbox[_-]?aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[332]":   "mapbox[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[333]":   "mapbox[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[334]":   "mapbox[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[335]":   "manifest[_-]?app[_-]?url(=| =|:| :)",
	"credentials-disclosure[336]":   "manifest[_-]?app[_-]?token(=| =|:| :)",
	"credentials-disclosure[337]":   "mandrill[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[338]":   "managementapiaccesstoken(=| =|:| :)",
	"credentials-disclosure[339]":   "management[_-]?token(=| =|:| :)",
	"credentials-disclosure[340]":   "manage[_-]?secret(=| =|:| :)",
	"credentials-disclosure[341]":   "manage[_-]?key(=| =|:| :)",
	"credentials-disclosure[342]":   "mailgun[_-]?secret[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[343]":   "mailgun[_-]?pub[_-]?key(=| =|:| :)",
	"credentials-disclosure[344]":   "mailgun[_-]?pub[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[345]":   "mailgun[_-]?priv[_-]?key(=| =|:| :)",
	"credentials-disclosure[346]":   "mailgun[_-]?password(=| =|:| :)",
	"credentials-disclosure[347]":   "mailgun[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[348]":   "mailgun[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[349]":   "mailer[_-]?password(=| =|:| :)",
	"credentials-disclosure[350]":   "mailchimp[_-]?key(=| =|:| :)",
	"credentials-disclosure[351]":   "mailchimp[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[352]":   "mail[_-]?password(=| =|:| :)",
	"credentials-disclosure[353]":   "magento[_-]?password(=| =|:| :)",
	"credentials-disclosure[354]":   "magento[_-]?auth[_-]?username (=| =|:| :)",
	"credentials-disclosure[355]":   "magento[_-]?auth[_-]?password(=| =|:| :)",
	"credentials-disclosure[356]":   "lottie[_-]?upload[_-]?cert[_-]?key[_-]?store[_-]?password(=| =|:| :)",
	"credentials-disclosure[357]":   "lottie[_-]?upload[_-]?cert[_-]?key[_-]?password(=| =|:| :)",
	"credentials-disclosure[358]":   "lottie[_-]?s3[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[359]":   "lottie[_-]?happo[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[360]":   "lottie[_-]?happo[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[361]":   "looker[_-]?test[_-]?runner[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[362]":   "ll[_-]?shared[_-]?key(=| =|:| :)",
	"credentials-disclosure[363]":   "ll[_-]?publish[_-]?url(=| =|:| :)",
	"credentials-disclosure[364]":   "linux[_-]?signing[_-]?key(=| =|:| :)",
	"credentials-disclosure[365]":   "linkedin[_-]?client[_-]?secretor lottie[_-]?s3[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[366]":   "lighthouse[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[367]":   "lektor[_-]?deploy[_-]?username(=| =|:| :)",
	"credentials-disclosure[368]":   "lektor[_-]?deploy[_-]?password(=| =|:| :)",
	"credentials-disclosure[369]":   "leanplum[_-]?key(=| =|:| :)",
	"credentials-disclosure[370]":   "kxoltsn3vogdop92m(=| =|:| :)",
	"credentials-disclosure[371]":   "kubeconfig(=| =|:| :)",
	"credentials-disclosure[372]":   "kubecfg[_-]?s3[_-]?path(=| =|:| :)",
	"credentials-disclosure[373]":   "kovan[_-]?private[_-]?key(=| =|:| :)",
	"credentials-disclosure[374]":   "keystore[_-]?pass(=| =|:| :)",
	"credentials-disclosure[375]":   "kafka[_-]?rest[_-]?url(=| =|:| :)",
	"credentials-disclosure[376]":   "kafka[_-]?instance[_-]?name(=| =|:| :)",
	"credentials-disclosure[377]":   "kafka[_-]?admin[_-]?url(=| =|:| :)",
	"credentials-disclosure[378]":   "jwt[_-]?secret(=| =|:| :)",
	"credentials-disclosure[379]":   "jdbc:mysql(=| =|:| :)",
	"credentials-disclosure[380]":   "jdbc[_-]?host(=| =|:| :)",
	"credentials-disclosure[381]":   "jdbc[_-]?databaseurl(=| =|:| :)",
	"credentials-disclosure[382]":   "itest[_-]?gh[_-]?token(=| =|:| :)",
	"credentials-disclosure[383]":   "ios[_-]?docs[_-]?deploy[_-]?token(=| =|:| :)",
	"credentials-disclosure[384]":   "internal[_-]?secrets(=| =|:| :)",
	"credentials-disclosure[385]":   "integration[_-]?test[_-]?appid(=| =|:| :)",
	"credentials-disclosure[386]":   "integration[_-]?test[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[387]":   "index[_-]?name(=| =|:| :)",
	"credentials-disclosure[388]":   "ij[_-]?repo[_-]?username(=| =|:| :)",
	"credentials-disclosure[389]":   "ij[_-]?repo[_-]?password(=| =|:| :)",
	"credentials-disclosure[390]":   "hub[_-]?dxia2[_-]?password(=| =|:| :)",
	"credentials-disclosure[391]":   "homebrew[_-]?github[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[392]":   "hockeyapp[_-]?token(=| =|:| :)",
	"credentials-disclosure[393]":   "heroku[_-]?token(=| =|:| :)",
	"credentials-disclosure[394]":   "heroku[_-]?email(=| =|:| :)",
	"credentials-disclosure[395]":   "heroku[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[396]":   "hb[_-]?codesign[_-]?key[_-]?pass(=| =|:| :)",
	"credentials-disclosure[397]":   "hb[_-]?codesign[_-]?gpg[_-]?pass(=| =|:| :)",
	"credentials-disclosure[398]":   "hab[_-]?key(=| =|:| :)",
	"credentials-disclosure[399]":   "hab[_-]?auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[400]":   "grgit[_-]?user(=| =|:| :)",
	"credentials-disclosure[401]":   "gren[_-]?github[_-]?token(=| =|:| :)",
	"credentials-disclosure[402]":   "gradle[_-]?signing[_-]?password(=| =|:| :)",
	"credentials-disclosure[403]":   "gradle[_-]?signing[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[404]":   "gradle[_-]?publish[_-]?secret(=| =|:| :)",
	"credentials-disclosure[405]":   "gradle[_-]?publish[_-]?key(=| =|:| :)",
	"credentials-disclosure[406]":   "gpg[_-]?secret[_-]?keys(=| =|:| :)",
	"credentials-disclosure[407]":   "gpg[_-]?private[_-]?key(=| =|:| :)",
	"credentials-disclosure[408]":   "gpg[_-]?passphrase(=| =|:| :)",
	"credentials-disclosure[409]":   "gpg[_-]?ownertrust(=| =|:| :)",
	"credentials-disclosure[410]":   "gpg[_-]?keyname(=| =|:| :)",
	"credentials-disclosure[411]":   "gpg[_-]?key[_-]?name(=| =|:| :)",
	"credentials-disclosure[412]":   "google[_-]?private[_-]?key(=| =|:| :)",
	"credentials-disclosure[413]":   "google[_-]?maps[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[414]":   "google[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[415]":   "google[_-]?client[_-]?id(=| =|:| :)",
	"credentials-disclosure[416]":   "google[_-]?client[_-]?email(=| =|:| :)",
	"credentials-disclosure[417]":   "google[_-]?account[_-]?type(=| =|:| :)",
	"credentials-disclosure[418]":   "gogs[_-]?password(=| =|:| :)",
	"credentials-disclosure[419]":   "gitlab[_-]?user[_-]?email(=| =|:| :)",
	"credentials-disclosure[420]":   "github[_-]?tokens(=| =|:| :)",
	"credentials-disclosure[421]":   "github[_-]?token(=| =|:| :)",
	"credentials-disclosure[422]":   "github[_-]?repo(=| =|:| :)",
	"credentials-disclosure[423]":   "github[_-]?release[_-]?token(=| =|:| :)",
	"credentials-disclosure[424]":   "github[_-]?pwd(=| =|:| :)",
	"credentials-disclosure[425]":   "github[_-]?password(=| =|:| :)",
	"credentials-disclosure[426]":   "github[_-]?oauth[_-]?token(=| =|:| :)",
	"credentials-disclosure[427]":   "github[_-]?oauth(=| =|:| :)",
	"credentials-disclosure[428]":   "github[_-]?key(=| =|:| :)",
	"credentials-disclosure[429]":   "github[_-]?hunter[_-]?username(=| =|:| :)",
	"credentials-disclosure[430]":   "github[_-]?hunter[_-]?token(=| =|:| :)",
	"credentials-disclosure[431]":   "github[_-]?deployment[_-]?token(=| =|:| :)",
	"credentials-disclosure[432]":   "github[_-]?deploy[_-]?hb[_-]?doc[_-]?pass(=| =|:| :)",
	"credentials-disclosure[433]":   "github[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[434]":   "github[_-]?auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[435]":   "github[_-]?auth(=| =|:| :)",
	"credentials-disclosure[436]":   "github[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[437]":   "github[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[438]":   "github[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[439]":   "git[_-]?token(=| =|:| :)",
	"credentials-disclosure[440]":   "git[_-]?name(=| =|:| :)",
	"credentials-disclosure[441]":   "git[_-]?email(=| =|:| :)",
	"credentials-disclosure[442]":   "git[_-]?committer[_-]?name(=| =|:| :)",
	"credentials-disclosure[443]":   "git[_-]?committer[_-]?email(=| =|:| :)",
	"credentials-disclosure[444]":   "git[_-]?author[_-]?name(=| =|:| :)",
	"credentials-disclosure[445]":   "git[_-]?author[_-]?email(=| =|:| :)",
	"credentials-disclosure[446]":   "ghost[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[447]":   "ghb[_-]?token(=| =|:| :)",
	"credentials-disclosure[448]":   "gh[_-]?unstable[_-]?oauth[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[449]":   "gh[_-]?token(=| =|:| :)",
	"credentials-disclosure[450]":   "gh[_-]?repo[_-]?token(=| =|:| :)",
	"credentials-disclosure[451]":   "gh[_-]?oauth[_-]?token(=| =|:| :)",
	"credentials-disclosure[452]":   "gh[_-]?oauth[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[453]":   "gh[_-]?next[_-]?unstable[_-]?oauth[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[454]":   "gh[_-]?next[_-]?unstable[_-]?oauth[_-]?client[_-]?id(=| =|:| :)",
	"credentials-disclosure[455]":   "gh[_-]?next[_-]?oauth[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[456]":   "gh[_-]?email(=| =|:| :)",
	"credentials-disclosure[457]":   "gh[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[458]":   "gcs[_-]?bucket(=| =|:| :)",
	"credentials-disclosure[459]":   "gcr[_-]?password(=| =|:| :)",
	"credentials-disclosure[460]":   "gcloud[_-]?service[_-]?key(=| =|:| :)",
	"credentials-disclosure[461]":   "gcloud[_-]?project(=| =|:| :)",
	"credentials-disclosure[462]":   "gcloud[_-]?bucket(=| =|:| :)",
	"credentials-disclosure[463]":   "ftp[_-]?username(=| =|:| :)",
	"credentials-disclosure[464]":   "ftp[_-]?user(=| =|:| :)",
	"credentials-disclosure[465]":   "ftp[_-]?pw(=| =|:| :)",
	"credentials-disclosure[466]":   "ftp[_-]?password(=| =|:| :)",
	"credentials-disclosure[467]":   "ftp[_-]?login(=| =|:| :)",
	"credentials-disclosure[468]":   "ftp[_-]?host(=| =|:| :)",
	"credentials-disclosure[469]":   "fossa[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[470]":   "flickr[_-]?api[_-]?secret(=| =|:| :)",
	"credentials-disclosure[471]":   "flickr[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[472]":   "flask[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[473]":   "firefox[_-]?secret(=| =|:| :)",
	"credentials-disclosure[474]":   "firebase[_-]?token(=| =|:| :)",
	"credentials-disclosure[475]":   "firebase[_-]?project[_-]?develop(=| =|:| :)",
	"credentials-disclosure[476]":   "firebase[_-]?key(=| =|:| :)",
	"credentials-disclosure[477]":   "firebase[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[478]":   "firebase[_-]?api[_-]?json(=| =|:| :)",
	"credentials-disclosure[479]":   "file[_-]?password(=| =|:| :)",
	"credentials-disclosure[480]":   "exp[_-]?password(=| =|:| :)",
	"credentials-disclosure[481]":   "eureka[_-]?awssecretkey(=| =|:| :)",
	"credentials-disclosure[482]":   "env[_-]?sonatype[_-]?password(=| =|:| :)",
	"credentials-disclosure[483]":   "env[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[484]":   "env[_-]?secret(=| =|:| :)",
	"credentials-disclosure[485]":   "env[_-]?key(=| =|:| :)",
	"credentials-disclosure[486]":   "env[_-]?heroku[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[487]":   "env[_-]?github[_-]?oauth[_-]?token(=| =|:| :)",
	"credentials-disclosure[488]":   "end[_-]?user[_-]?password(=| =|:| :)",
	"credentials-disclosure[489]":   "encryption[_-]?password(=| =|:| :)",
	"credentials-disclosure[490]":   "elasticsearch[_-]?password(=| =|:| :)",
	"credentials-disclosure[491]":   "elastic[_-]?cloud[_-]?auth(=| =|:| :)",
	"credentials-disclosure[492]":   "dsonar[_-]?projectkey(=| =|:| :)",
	"credentials-disclosure[493]":   "dsonar[_-]?login(=| =|:| :)",
	"credentials-disclosure[494]":   "droplet[_-]?travis[_-]?password(=| =|:| :)",
	"credentials-disclosure[495]":   "dropbox[_-]?oauth[_-]?bearer(=| =|:| :)",
	"credentials-disclosure[496]":   "doordash[_-]?auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[497]":   "dockerhubpassword(=| =|:| :)",
	"credentials-disclosure[498]":   "dockerhub[_-]?password(=| =|:| :)",
	"credentials-disclosure[499]":   "docker[_-]?token(=| =|:| :)",
	"credentials-disclosure[500]":   "docker[_-]?postgres[_-]?url(=| =|:| :)",
	"credentials-disclosure[501]":   "docker[_-]?password(=| =|:| :)",
	"credentials-disclosure[502]":   "docker[_-]?passwd(=| =|:| :)",
	"credentials-disclosure[503]":   "docker[_-]?pass(=| =|:| :)",
	"credentials-disclosure[504]":   "docker[_-]?key(=| =|:| :)",
	"credentials-disclosure[505]":   "docker[_-]?hub[_-]?password(=| =|:| :)",
	"credentials-disclosure[506]":   "digitalocean[_-]?ssh[_-]?key[_-]?ids(=| =|:| :)",
	"credentials-disclosure[507]":   "digitalocean[_-]?ssh[_-]?key[_-]?body(=| =|:| :)",
	"credentials-disclosure[508]":   "digitalocean[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[509]":   "dgpg[_-]?passphrase(=| =|:| :)",
	"credentials-disclosure[510]":   "deploy[_-]?user(=| =|:| :)",
	"credentials-disclosure[511]":   "deploy[_-]?token(=| =|:| :)",
	"credentials-disclosure[512]":   "deploy[_-]?secure(=| =|:| :)",
	"credentials-disclosure[513]":   "deploy[_-]?password(=| =|:| :)",
	"credentials-disclosure[514]":   "ddgc[_-]?github[_-]?token(=| =|:| :)",
	"credentials-disclosure[515]":   "ddg[_-]?test[_-]?email[_-]?pw(=| =|:| :)",
	"credentials-disclosure[516]":   "ddg[_-]?test[_-]?email(=| =|:| :)",
	"credentials-disclosure[517]":   "db[_-]?username(=| =|:| :)",
	"credentials-disclosure[518]":   "db[_-]?user(=| =|:| :)",
	"credentials-disclosure[519]":   "db[_-]?pw(=| =|:| :)",
	"credentials-disclosure[520]":   "db[_-]?password(=| =|:| :)",
	"credentials-disclosure[521]":   "db[_-]?host(=| =|:| :)",
	"credentials-disclosure[522]":   "db[_-]?database(=| =|:| :)",
	"credentials-disclosure[523]":   "db[_-]?connection(=| =|:| :)",
	"credentials-disclosure[524]":   "datadog[_-]?app[_-]?key(=| =|:| :)",
	"credentials-disclosure[525]":   "datadog[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[526]":   "database[_-]?username(=| =|:| :)",
	"credentials-disclosure[527]":   "database[_-]?user(=| =|:| :)",
	"credentials-disclosure[528]":   "database[_-]?port(=| =|:| :)",
	"credentials-disclosure[529]":   "database[_-]?password(=| =|:| :)",
	"credentials-disclosure[530]":   "database[_-]?name(=| =|:| :)",
	"credentials-disclosure[531]":   "database[_-]?host(=| =|:| :)",
	"credentials-disclosure[532]":   "danger[_-]?github[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[533]":   "cypress[_-]?record[_-]?key(=| =|:| :)",
	"credentials-disclosure[534]":   "coverity[_-]?scan[_-]?token(=| =|:| :)",
	"credentials-disclosure[535]":   "coveralls[_-]?token(=| =|:| :)",
	"credentials-disclosure[536]":   "coveralls[_-]?repo[_-]?token(=| =|:| :)",
	"credentials-disclosure[537]":   "coveralls[_-]?api[_-]?token(=| =|:| :)",
	"credentials-disclosure[538]":   "cos[_-]?secrets(=| =|:| :)",
	"credentials-disclosure[539]":   "conversation[_-]?username(=| =|:| :)",
	"credentials-disclosure[540]":   "conversation[_-]?password(=| =|:| :)",
	"credentials-disclosure[541]":   "contentful[_-]?v2[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[542]":   "contentful[_-]?test[_-]?org[_-]?cma[_-]?token(=| =|:| :)",
	"credentials-disclosure[543]":   "contentful[_-]?php[_-]?management[_-]?test[_-]?token(=| =|:| :)",
	"credentials-disclosure[544]":   "contentful[_-]?management[_-]?api[_-]?access[_-]?token[_-]?new(=| =|:| :)",
	"credentials-disclosure[545]":   "contentful[_-]?management[_-]?api[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[546]":   "contentful[_-]?integration[_-]?management[_-]?token(=| =|:| :)",
	"credentials-disclosure[547]":   "contentful[_-]?cma[_-]?test[_-]?token(=| =|:| :)",
	"credentials-disclosure[548]":   "contentful[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[549]":   "consumerkey(=| =|:| :)",
	"credentials-disclosure[550]":   "consumer[_-]?key(=| =|:| :)",
	"credentials-disclosure[551]":   "conekta[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[552]":   "coding[_-]?token(=| =|:| :)",
	"credentials-disclosure[553]":   "codecov[_-]?token(=| =|:| :)",
	"credentials-disclosure[554]":   "codeclimate[_-]?repo[_-]?token(=| =|:| :)",
	"credentials-disclosure[555]":   "codacy[_-]?project[_-]?token(=| =|:| :)",
	"credentials-disclosure[556]":   "cocoapods[_-]?trunk[_-]?token(=| =|:| :)",
	"credentials-disclosure[557]":   "cocoapods[_-]?trunk[_-]?email(=| =|:| :)",
	"credentials-disclosure[558]":   "cn[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[559]":   "cn[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[560]":   "clu[_-]?ssh[_-]?private[_-]?key[_-]?base64(=| =|:| :)",
	"credentials-disclosure[561]":   "clu[_-]?repo[_-]?url(=| =|:| :)",
	"credentials-disclosure[562]":   "cloudinary[_-]?url[_-]?staging(=| =|:| :)",
	"credentials-disclosure[563]":   "cloudinary[_-]?url(=| =|:| :)",
	"credentials-disclosure[564]":   "cloudflare[_-]?email(=| =|:| :)",
	"credentials-disclosure[565]":   "cloudflare[_-]?auth[_-]?key(=| =|:| :)",
	"credentials-disclosure[566]":   "cloudflare[_-]?auth[_-]?email(=| =|:| :)",
	"credentials-disclosure[567]":   "cloudflare[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[568]":   "cloudant[_-]?service[_-]?database(=| =|:| :)",
	"credentials-disclosure[569]":   "cloudant[_-]?processed[_-]?database(=| =|:| :)",
	"credentials-disclosure[570]":   "cloudant[_-]?password(=| =|:| :)",
	"credentials-disclosure[571]":   "cloudant[_-]?parsed[_-]?database(=| =|:| :)",
	"credentials-disclosure[572]":   "cloudant[_-]?order[_-]?database(=| =|:| :)",
	"credentials-disclosure[573]":   "cloudant[_-]?instance(=| =|:| :)",
	"credentials-disclosure[574]":   "cloudant[_-]?database(=| =|:| :)",
	"credentials-disclosure[575]":   "cloudant[_-]?audited[_-]?database(=| =|:| :)",
	"credentials-disclosure[576]":   "cloudant[_-]?archived[_-]?database(=| =|:| :)",
	"credentials-disclosure[577]":   "cloud[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[578]":   "clojars[_-]?password(=| =|:| :)",
	"credentials-disclosure[579]":   "client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[580]":   "cli[_-]?e2e[_-]?cma[_-]?token(=| =|:| :)",
	"credentials-disclosure[581]":   "claimr[_-]?token(=| =|:| :)",
	"credentials-disclosure[582]":   "claimr[_-]?superuser(=| =|:| :)",
	"credentials-disclosure[583]":   "claimr[_-]?db(=| =|:| :)",
	"credentials-disclosure[584]":   "claimr[_-]?database(=| =|:| :)",
	"credentials-disclosure[585]":   "ci[_-]?user[_-]?token(=| =|:| :)",
	"credentials-disclosure[586]":   "ci[_-]?server[_-]?name(=| =|:| :)",
	"credentials-disclosure[587]":   "ci[_-]?registry[_-]?user(=| =|:| :)",
	"credentials-disclosure[588]":   "ci[_-]?project[_-]?url(=| =|:| :)",
	"credentials-disclosure[589]":   "ci[_-]?deploy[_-]?password(=| =|:| :)",
	"credentials-disclosure[590]":   "chrome[_-]?refresh[_-]?token(=| =|:| :)",
	"credentials-disclosure[591]":   "cheverny[_-]?token(=| =|:| :)",
	"credentials-disclosure[592]":   "cf[_-]?password(=| =|:| :)",
	"credentials-disclosure[593]":   "certificate[_-]?password(=| =|:| :)",
	"credentials-disclosure[594]":   "censys[_-]?secret(=| =|:| :)",
	"credentials-disclosure[595]":   "cattle[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[596]":   "cattle[_-]?agent[_-]?instance[_-]?auth(=| =|:| :)",
	"credentials-disclosure[597]":   "cattle[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[598]":   "cargo[_-]?token(=| =|:| :)",
	"credentials-disclosure[599]":   "cache[_-]?s3[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[600]":   "bx[_-]?username(=| =|:| :)",
	"credentials-disclosure[601]":   "bx[_-]?password(=| =|:| :)",
	"credentials-disclosure[602]":   "bundlesize[_-]?github[_-]?token(=| =|:| :)",
	"credentials-disclosure[603]":   "built[_-]?branch[_-]?deploy[_-]?key(=| =|:| :)",
	"credentials-disclosure[604]":   "bucketeer[_-]?aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[605]":   "bucketeer[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[606]":   "browserstack[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[607]":   "browser[_-]?stack[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[608]":   "brackets[_-]?repo[_-]?oauth[_-]?token(=| =|:| :)",
	"credentials-disclosure[609]":   "bluemix[_-]?username(=| =|:| :)",
	"credentials-disclosure[610]":   "bluemix[_-]?pwd(=| =|:| :)",
	"credentials-disclosure[611]":   "bluemix[_-]?password(=| =|:| :)",
	"credentials-disclosure[612]":   "bluemix[_-]?pass[_-]?prod(=| =|:| :)",
	"credentials-disclosure[613]":   "bluemix[_-]?pass(=| =|:| :)",
	"credentials-disclosure[614]":   "bluemix[_-]?auth(=| =|:| :)",
	"credentials-disclosure[615]":   "bluemix[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[616]":   "bintraykey(=| =|:| :)",
	"credentials-disclosure[617]":   "bintray[_-]?token(=| =|:| :)",
	"credentials-disclosure[618]":   "bintray[_-]?key(=| =|:| :)",
	"credentials-disclosure[619]":   "bintray[_-]?gpg[_-]?password(=| =|:| :)",
	"credentials-disclosure[620]":   "bintray[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[621]":   "bintray[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[622]":   "b2[_-]?bucket(=| =|:| :)",
	"credentials-disclosure[623]":   "b2[_-]?app[_-]?key(=| =|:| :)",
	"credentials-disclosure[624]":   "awssecretkey(=| =|:| :)",
	"credentials-disclosure[625]":   "awscn[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[626]":   "awscn[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[627]":   "awsaccesskeyid(=| =|:| :)",
	"credentials-disclosure[628]":   "aws[_-]?ses[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[629]":   "aws[_-]?ses[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[630]":   "aws[_-]?secrets(=| =|:| :)",
	"credentials-disclosure[631]":   "aws[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[632]":   "aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[633]":   "aws[_-]?secret(=| =|:| :)",
	"credentials-disclosure[634]":   "aws[_-]?key(=| =|:| :)",
	"credentials-disclosure[635]":   "aws[_-]?config[_-]?secretaccesskey(=| =|:| :)",
	"credentials-disclosure[636]":   "aws[_-]?config[_-]?accesskeyid(=| =|:| :)",
	"credentials-disclosure[637]":   "aws[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[638]":   "aws[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[639]":   "aws[_-]?access(=| =|:| :)",
	"credentials-disclosure[640]":   "author[_-]?npm[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[641]":   "author[_-]?email[_-]?addr(=| =|:| :)",
	"credentials-disclosure[642]":   "auth0[_-]?client[_-]?secret(=| =|:| :)",
	"credentials-disclosure[643]":   "auth0[_-]?api[_-]?clientsecret(=| =|:| :)",
	"credentials-disclosure[645]":   "auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[646]":   "assistant[_-]?iam[_-]?apikey(=| =|:| :)",
	"credentials-disclosure[647]":   "artifacts[_-]?secret(=| =|:| :)",
	"credentials-disclosure[648]":   "artifacts[_-]?key(=| =|:| :)",
	"credentials-disclosure[649]":   "artifacts[_-]?bucket(=| =|:| :)",
	"credentials-disclosure[650]":   "artifacts[_-]?aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[651]":   "artifacts[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)",
	"credentials-disclosure[652]":   "artifactory[_-]?key(=| =|:| :)",
	"credentials-disclosure[653]":   "argos[_-]?token(=| =|:| :)",
	"credentials-disclosure[654]":   "apple[_-]?id[_-]?password(=| =|:| :)",
	"credentials-disclosure[655]":   "appclientsecret(=| =|:| :)",
	"credentials-disclosure[656]":   "app[_-]?token(=| =|:| :)",
	"credentials-disclosure[657]":   "app[_-]?secrete(=| =|:| :)",
	"credentials-disclosure[658]":   "app[_-]?report[_-]?token[_-]?key(=| =|:| :)",
	"credentials-disclosure[659]":   "app[_-]?bucket[_-]?perm(=| =|:| :)",
	"credentials-disclosure[660]":   "apigw[_-]?access[_-]?token(=| =|:| :)",
	"credentials-disclosure[661]":   "apiary[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[662]":   "api[_-]?secret(=| =|:| :)",
	"credentials-disclosure[663]":   "api[_-]?key[_-]?sid(=| =|:| :)",
	"credentials-disclosure[664]":   "api[_-]?key[_-]?secret(=| =|:| :)",
	"credentials-disclosure[666]":   "aos[_-]?sec(=| =|:| :)",
	"credentials-disclosure[667]":   "aos[_-]?key(=| =|:| :)",
	"credentials-disclosure[668]":   "ansible[_-]?vault[_-]?password(=| =|:| :)",
	"credentials-disclosure[669]":   "android[_-]?docs[_-]?deploy[_-]?token(=| =|:| :)",
	"credentials-disclosure[670]":   "anaconda[_-]?token(=| =|:| :)",
	"credentials-disclosure[671]":   "amazon[_-]?secret[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[672]":   "amazon[_-]?bucket[_-]?name(=| =|:| :)",
	"credentials-disclosure[673]":   "alicloud[_-]?secret[_-]?key(=| =|:| :)",
	"credentials-disclosure[674]":   "alicloud[_-]?access[_-]?key(=| =|:| :)",
	"credentials-disclosure[675]":   "alias[_-]?pass(=| =|:| :)",
	"credentials-disclosure[676]":   "algolia[_-]?search[_-]?key[_-]?1(=| =|:| :)",
	"credentials-disclosure[677]":   "algolia[_-]?search[_-]?key(=| =|:| :)",
	"credentials-disclosure[678]":   "algolia[_-]?search[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[67rmt]": "algolia[_-]?api[_-]?key[_-]?mcm(=| =|:| :)",
	"credentials-disclosure[681]":   "algolia[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[682]":   "algolia[_-]?admin[_-]?key[_-]?mcm(=| =|:| :)",
	"credentials-disclosure[683]":   "algolia[_-]?admin[_-]?key[_-]?2(=| =|:| :)",
	"credentials-disclosure[684]":   "algolia[_-]?admin[_-]?key[_-]?1(=| =|:| :)",
	"credentials-disclosure[685]":   "adzerk[_-]?api[_-]?key(=| =|:| :)",
	"credentials-disclosure[686]":   "admin[_-]?email(=| =|:| :)",
	"credentials-disclosure[687]":   "account[_-]?sid(=| =|:| :)",
	"credentials-disclosure[688]":   "access[_-]?token(=| =|:| :)",
	"credentials-disclosure[689]":   "access[_-]?secret(=| =|:| :)",
	"credentials-disclosure[690]":   "access[_-]?key[_-]?secret(=| =|:| :)",
	"credentials-disclosure[691]":   "auth[_-]?token(=| =|:| :)",
	"credentials-disclosure[692]":   "NINTENDO_API",
	"credentials-disclosure[693]":   "token(=| =|:| :)",
}

func CreatHashSum(input string) (string, error) {
	hasher := md5.New()

	_, err := hasher.Write([]byte(input))
	if err != nil {
		return "", err
	}

	hashSum := hasher.Sum(nil)

	hashString := hex.EncodeToString(hashSum)

	return hashString, nil
}

func contains(s []string, str string) bool {
	for _, v := range s {
		if v == str {
			return true
		}
	}

	return false
}

func isUrl(url string) bool {
	s := false
	regex1, _ := regexp.MatchString("http", url)
	regex2, _ := regexp.MatchString("://", url)
	if regex1 == true && regex2 == true {

		s = true
	}
	return s
}
func requester(url string) string {

	response := ""
	client := &http.Client{}
	req, err := http.NewRequest("GET", url, nil)
	if err == nil {
		resp, err := client.Do(req)
		if err == nil {
			defer resp.Body.Close()

			body, _ := ioutil.ReadAll(resp.Body)
			response = string(body)

		}
	}
	return response
}
